/* =============================================
   egi-sink-checker / data.js
   メーカーを追加する場合はこのファイルの EGI_DATA 配列に追記してください。
   sink_sec_per_m が不明な場合は null を入れてください。
   ============================================= */

var EGI_DATA = [
  /* ---------- YAMASHITA ---------- */
  { maker:"YAMASHITA", series:"エギ王K",   size:"2.5号", type:"ベーシック",           weight_g:11.0,  sink_sec_per_m:5.0,  category:"アオリイカ",    affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3号",   type:"ベーシック",           weight_g:16.0,  sink_sec_per_m:3.0,  category:"アオリイカ",    affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3.5号", type:"ベーシック",           weight_g:22.0,  sink_sec_per_m:3.0,  category:"アオリイカ",    affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王K",   size:"4号",   type:"ベーシック",           weight_g:26.0,  sink_sec_per_m:3.0,  category:"アオリイカ",    affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3号",   type:"シャロー",             weight_g:15.0,  sink_sec_per_m:6.0,  category:"アオリイカ",    affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3号",   type:"スーパーシャロー",     weight_g:14.5,  sink_sec_per_m:8.0,  category:"アオリイカ",    affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3.5号", type:"シャロー",             weight_g:20.0,  sink_sec_per_m:6.0,  category:"アオリイカ",    affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3.5号", type:"スーパーシャロー",     weight_g:19.5,  sink_sec_per_m:8.0,  category:"アオリイカ",    affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王K",   size:"4号",   type:"シャロー",             weight_g:24.0,  sink_sec_per_m:6.0,  category:"アオリイカ",    affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3.5号", type:"黒潮スペシャル",       weight_g:22.0,  sink_sec_per_m:3.0,  category:"アオリイカ",    affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3.5号", type:"ディープ黒潮スペシャル", weight_g:25.0, sink_sec_per_m:2.0, category:"アオリイカ",    affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王K",   size:"4号",   type:"黒潮スペシャル",       weight_g:26.0,  sink_sec_per_m:3.0,  category:"アオリイカ",    affiliate_url:"" },

  { maker:"YAMASHITA", series:"エギ王LIVE",   size:"2号",   type:"ベーシック", weight_g:6.5,  sink_sec_per_m:5.5, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王LIVE",   size:"2.5号", type:"ベーシック", weight_g:10.0, sink_sec_per_m:5.5, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王LIVE",   size:"3号",   type:"ベーシック", weight_g:15.0, sink_sec_per_m:3.5, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王LIVE",   size:"3.5号", type:"ベーシック", weight_g:21.0, sink_sec_per_m:3.0, category:"アオリイカ", affiliate_url:"" },

  { maker:"YAMASHITA", series:"エギ王SEARCH", size:"2.5号", type:"ベーシック", weight_g:12.0, sink_sec_per_m:3.6, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王SEARCH", size:"3号",   type:"ベーシック", weight_g:17.0, sink_sec_per_m:3.2, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王SEARCH", size:"3.5号", type:"ベーシック", weight_g:24.0, sink_sec_per_m:2.8, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王SEARCH", size:"3号",   type:"シャロー",   weight_g:15.5, sink_sec_per_m:4.5, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王SEARCH", size:"3.5号", type:"シャロー",   weight_g:21.0, sink_sec_per_m:4.5, category:"アオリイカ", affiliate_url:"" },

  { maker:"YAMASHITA", series:"エギ王TR", size:"3号",   type:"TR", weight_g:21.0, sink_sec_per_m:1.5, category:"ティップラン", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王TR", size:"3.5号", type:"TR", weight_g:27.0, sink_sec_per_m:1.2, category:"ティップラン", affiliate_url:"" },

  { maker:"YAMASHITA", series:"NAORY レンジ シャロー",   size:"1.5号",  type:"シャロー",         weight_g:3.3,  sink_sec_per_m:8.5,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ シャロー",   size:"1.8号",  type:"シャロー",         weight_g:5.0,  sink_sec_per_m:10.0, category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ シャロー",   size:"2.2B号", type:"シャロー",         weight_g:8.0,  sink_sec_per_m:5.0,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ ベーシック", size:"1.5号",  type:"ベーシック",       weight_g:3.8,  sink_sec_per_m:4.5,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ ベーシック", size:"1.8号",  type:"ベーシック",       weight_g:6.0,  sink_sec_per_m:3.2,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ ベーシック", size:"2.2B号", type:"ベーシック",       weight_g:9.0,  sink_sec_per_m:2.8,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ ディープ",   size:"1.5号",  type:"ディープ",         weight_g:4.7,  sink_sec_per_m:3.0,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ ディープ",   size:"1.8号",  type:"ディープ",         weight_g:7.0,  sink_sec_per_m:2.5,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ ディープ",   size:"2.2B号", type:"ディープ",         weight_g:10.5, sink_sec_per_m:2.2,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"ナオリー サイトハンター", size:"1.0号",  type:"ベーシックシャロー", weight_g:1.5, sink_sec_per_m:8.5,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"ナオリー サイトハンター", size:"1.3号",  type:"ベーシックシャロー", weight_g:2.3, sink_sec_per_m:8.0,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギーノもぐもぐサーチ",  size:"3.2号",  type:"キビナゴ装着時",   weight_g:20.0, sink_sec_per_m:2.8,  category:"入門／エサ巻き系", affiliate_url:"" },
  { maker:"YAMASHITA", series:"ホバー", size:"2.0号", type:"単体", weight_g:6.0, sink_sec_per_m:8.0, category:"オモリグ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"ホバー", size:"2.5号", type:"単体", weight_g:9.0, sink_sec_per_m:8.0, category:"オモリグ", affiliate_url:"" },

  /* ---------- DUEL ---------- */
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ",         size:"2.5号", type:"ベーシック", weight_g:10.0, sink_sec_per_m:5.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ",         size:"3.0号", type:"ベーシック", weight_g:14.0, sink_sec_per_m:3.7,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ",         size:"3.5号", type:"ベーシック", weight_g:17.0, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター",           size:"2.5号", type:"ベーシック", weight_g:10.0, sink_sec_per_m:5.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター",           size:"3.0号", type:"ベーシック", weight_g:14.5, sink_sec_per_m:3.5,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター",           size:"3.5号", type:"ベーシック", weight_g:19.0, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"Ebi Q",                              size:"3.0号", type:"ベーシック", weight_g:15.5, sink_sec_per_m:4.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"Ebi Q",                              size:"3.5号", type:"ベーシック", weight_g:20.5, sink_sec_per_m:3.5,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ マグネットTG（マグパタ）", size:"3.0号", type:"ベーシック", weight_g:15.0, sink_sec_per_m:3.8,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ マグネットTG（マグパタ）", size:"3.5号", type:"ベーシック", weight_g:18.5, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"EQ（Egiオリジナル）",                size:"3.0号", type:"ベーシック", weight_g:14.5, sink_sec_per_m:3.7,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"EQ（Egiオリジナル）",                size:"3.5号", type:"ベーシック", weight_g:19.0, sink_sec_per_m:3.3,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"LQ ダーター",                        size:"3.0号", type:"ベーシック", weight_g:14.0, sink_sec_per_m:3.8,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"LQ ダーター",                        size:"3.5号", type:"ベーシック", weight_g:18.0, sink_sec_per_m:3.3,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ スロー",   size:"3.0号", type:"スロー",     weight_g:13.0, sink_sec_per_m:6.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ スロー",   size:"3.5号", type:"スロー",     weight_g:15.5, sink_sec_per_m:6.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ ラトル",   size:"2.5号", type:"ラトル",     weight_g:10.0, sink_sec_per_m:3.9,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ ラトル",   size:"3.0号", type:"ラトル",     weight_g:14.0, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ ラトル",   size:"3.5号", type:"ラトル",     weight_g:17.0, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト プラス",          size:"3.0号", type:"ベーシック", weight_g:14.5, sink_sec_per_m:3.5,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト プラス",          size:"3.5号", type:"ベーシック", weight_g:19.5, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター SS",        size:"3.0号", type:"SS",         weight_g:13.0, sink_sec_per_m:8.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター SS",        size:"3.5号", type:"SS",         weight_g:17.5, sink_sec_per_m:8.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター ラトル",    size:"2.5号", type:"ラトル",     weight_g:10.0, sink_sec_per_m:5.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター ラトル",    size:"3.0号", type:"ラトル",     weight_g:14.5, sink_sec_per_m:3.5,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター ラトル",    size:"3.5号", type:"ラトル",     weight_g:19.0, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"Ebi Q TR",                           size:"3.0号", type:"TR",         weight_g:23.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DUEL", series:"Ebi Q TR",                           size:"3.5号", type:"TR",         weight_g:28.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },

  /* ---------- DAIWA ---------- */
  { maker:"DAIWA", series:"エメラルダス アモラスジョイント",             size:"2.5号",     type:"ベーシック", weight_g:11.0, sink_sec_per_m:4.75, category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス アモラスジョイント",             size:"3.0号",     type:"ベーシック", weight_g:13.5, sink_sec_per_m:4.25, category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス アモラスジョイント",             size:"3.5号",     type:"ベーシック", weight_g:22.5, sink_sec_per_m:3.75, category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス アモラスジョイント TypeS",       size:"2.5号",     type:"TypeS",      weight_g:10.0, sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス アモラスジョイント TypeS",       size:"3.0号",     type:"TypeS",      weight_g:12.5, sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス アモラスジョイント TypeS",       size:"3.5号",     type:"TypeS",      weight_g:21.0, sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス シャイン LC レーザーインパクト", size:"2.5号",     type:"ベーシック", weight_g:12.0, sink_sec_per_m:4.75, category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス シャイン LC レーザーインパクト", size:"3.0号",     type:"ベーシック", weight_g:14.0, sink_sec_per_m:4.25, category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス シャイン LC レーザーインパクト", size:"3.5号",     type:"ベーシック", weight_g:18.5, sink_sec_per_m:3.75, category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダスシャインLC TypeS",                size:"3.5号",     type:"TypeS",      weight_g:18.4, sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル",              size:"2.0号",     type:"ラトル",     weight_g:6.5,  sink_sec_per_m:6.5,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル",              size:"2.5号",     type:"ラトル",     weight_g:10.0, sink_sec_per_m:5.5,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル",              size:"3.0号",     type:"ラトル",     weight_g:14.5, sink_sec_per_m:4.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル",              size:"3.5号",     type:"ラトル",     weight_g:21.5, sink_sec_per_m:3.5,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル typeS",        size:"2.5号",     type:"ラトルTypeS", weight_g:9.5, sink_sec_per_m:6.5,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル typeS",        size:"3.0号",     type:"ラトルTypeS", weight_g:14.0,sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル typeS",        size:"3.5号",     type:"ラトルTypeS", weight_g:20.5,sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ダートLC",                       size:"3.0号",     type:"ベーシック", weight_g:16.0, sink_sec_per_m:4.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダスダートLC TypeS",                  size:"3.5号",     type:"TypeS",      weight_g:19.0, sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボートジョイント",               size:"3.0号-25g", type:"ボート",     weight_g:25.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボートジョイント",               size:"3.5号-30g", type:"ボート",     weight_g:30.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II（ノーマルバージョン）", size:"2.75号-25g", type:"ボート",    weight_g:25.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II（ノーマルバージョン）", size:"3号-25g",   type:"ボート",    weight_g:25.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II（ノーマルバージョン）", size:"3号-35g",   type:"ボート",    weight_g:35.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II RV（ラトルバージョン）", size:"2.75号-25g", type:"ラトル",  weight_g:25.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II RV（ラトルバージョン）", size:"3号-25g",   type:"ラトル",  weight_g:25.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II RV（ラトルバージョン）", size:"3号-35g",   type:"ラトル",  weight_g:35.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II / ボート II RV 3.5-50", size:"3.5号-50g", type:"ボート",  weight_g:50.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II / ボート II RV 3.5-50", size:"3.5号-50g", type:"ラトル",  weight_g:50.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダスボート RV（ラトルバージョン）",    size:"3.0号-25g", type:"ラトル",  weight_g:25.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダスボート RV（ラトルバージョン）",    size:"3.5号-30g", type:"ラトル",  weight_g:30.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },

  /* ---------- SHIMANO ---------- */
  { maker:"SHIMANO", series:"セッピー",                             size:"1.5号", type:"ベーシック",       weight_g:4.5,  sink_sec_per_m:3.7, category:"ライトエギング", affiliate_url:"" },
  { maker:"SHIMANO", series:"セッピー",                             size:"1.8号", type:"ベーシック",       weight_g:7.0,  sink_sec_per_m:3.5, category:"ライトエギング", affiliate_url:"" },
  { maker:"SHIMANO", series:"セッピー",                             size:"2.2号", type:"ベーシック",       weight_g:9.0,  sink_sec_per_m:2.2, category:"ライトエギング", affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ フラッシュブースト",          size:"2.5号", type:"ベーシック",       weight_g:10.0, sink_sec_per_m:4.0, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ フラッシュブースト",          size:"3.0号", type:"ベーシック",       weight_g:15.0, sink_sec_per_m:3.0, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ フラッシュブースト",          size:"3.5号", type:"ベーシック",       weight_g:19.0, sink_sec_per_m:3.7, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ エクスカウンター",            size:"3.5号", type:"ベーシック",       weight_g:19.0, sink_sec_per_m:3.7, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ エクスカウンター",            size:"3.8号", type:"ベーシック",       weight_g:24.0, sink_sec_per_m:3.5, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ シャロー",                    size:"3.5号", type:"ベーシック",       weight_g:18.5, sink_sec_per_m:6.0, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ シャロー フラッシュブースト", size:"3.0号", type:"フラッシュブースト", weight_g:13.8, sink_sec_per_m:5.4, category:"アオリイカ",  affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ シャロー フラッシュブースト", size:"3.5号", type:"フラッシュブースト", weight_g:18.5, sink_sec_per_m:6.0, category:"アオリイカ",  affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ ディープ フラッシュブースト", size:"3.5号", type:"ディープ",         weight_g:23.0, sink_sec_per_m:1.9, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ ロングアピール ジェットブースト", size:"3.0号", type:"ロングアピール", weight_g:13.0, sink_sec_per_m:4.2, category:"アオリイカ", affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ ロングアピール ジェットブースト", size:"3.5号", type:"ロングアピール", weight_g:17.0, sink_sec_per_m:7.4, category:"アオリイカ", affiliate_url:"" },
];
