/* =============================================
   egi-sink-checker / data.js
   メーカーを追加する場合はこのファイルの EGI_DATA 配列に追記してください。
   sink_sec_per_m が不明な場合は null を入れてください。
   affiliate_url はバッククォート（`）で囲む。リンクなしの場合は "" のまま。
   ============================================= */




   
var EGI_DATA = [
  /* ---------- YAMASHITA ---------- */
  { maker:"YAMASHITA", series:"エギ王K",   size:"2.5号", type:"ベーシック",           weight_g:11.0,  sink_sec_per_m:5.0,  category:"アオリイカ",    affiliate_url:`<a href="//af.moshimo.com/af/c/click?a_id=5211705&p_id=54&pc_id=54&pl_id=616&s_v=b5Rz2P0601xu&url=https%3A%2F%2Fitem.rakuten.co.jp%2Ffishingsanin%2F10026457%2F%3Frafcid%3Dwsc_i_is_c7c582dc-0853-4585-9176-66e2a26d9c5b" target="_blank" ><img src="https://thumbnail.image.rakuten.co.jp/@0_mall/fishingsanin/cabinet/12595610/egio-k.jpg?_ex=320x320"></a><img src="//i.moshimo.com/af/i/impression?a_id=5211705&p_id=54&pc_id=54&pl_id=616" width="1" height="1" style="border:none;">` },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3号",   type:"ベーシック",           weight_g:16.0,  sink_sec_per_m:3.0,  category:"アオリイカ",    affiliate_url:`<a href="//af.moshimo.com/af/c/click?a_id=5211705&p_id=54&pc_id=54&pl_id=616&s_v=b5Rz2P0601xu&url=https%3A%2F%2Fitem.rakuten.co.jp%2Fyokootsurigu%2F4510001595093%2F%3Frafcid%3Dwsc_i_is_c7c582dc-0853-4585-9176-66e2a26d9c5b" target="_blank" ><img src="https://thumbnail.image.rakuten.co.jp/@0_mall/yokootsurigu/cabinet/image_07/4510001595093.jpg?_ex=320x320"></a><img src="//i.moshimo.com/af/i/impression?a_id=5211705&p_id=54&pc_id=54&pl_id=616" width="1" height="1" style="border:none;">` },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3.5号", type:"ベーシック",           weight_g:22.0,  sink_sec_per_m:3.0,  category:"アオリイカ",    affiliate_url:`<a href="//af.moshimo.com/af/c/click?a_id=5211705&p_id=54&pc_id=54&pl_id=616&s_v=b5Rz2P0601xu&url=https%3A%2F%2Fitem.rakuten.co.jp%2Fyokootsurigu%2F4510001594591%2F%3Frafcid%3Dwsc_i_is_c7c582dc-0853-4585-9176-66e2a26d9c5b" target="_blank" ><img src="https://thumbnail.image.rakuten.co.jp/@0_mall/yokootsurigu/cabinet/image_07/4510001594591.jpg?_ex=320x320"></a><img src="//i.moshimo.com/af/i/impression?a_id=5211705&p_id=54&pc_id=54&pl_id=616" width="1" height="1" style="border:none;">` },
  { maker:"YAMASHITA", series:"エギ王K",   size:"4号",   type:"ベーシック",           weight_g:26.0,  sink_sec_per_m:3.0,  category:"アオリイカ",    affiliate_url:`<a href="//af.moshimo.com/af/c/click?a_id=5211705&p_id=54&pc_id=54&pl_id=616&s_v=b5Rz2P0601xu&url=https%3A%2F%2Fitem.rakuten.co.jp%2Fyadaya%2F10003606%2F%3Frafcid%3Dwsc_i_is_c7c582dc-0853-4585-9176-66e2a26d9c5b" target="_blank" ><img src="https://thumbnail.image.rakuten.co.jp/@0_mall/yadaya/cabinet/03644517/005-1.jpg?_ex=320x320"></a><img src="//i.moshimo.com/af/i/impression?a_id=5211705&p_id=54&pc_id=54&pl_id=616" width="1" height="1" style="border:none;">` },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3号",   type:"シャロー",             weight_g:15.0,  sink_sec_per_m:6.0,  category:"アオリイカ",    affiliate_url:`<a href="//af.moshimo.com/af/c/click?a_id=5211705&p_id=54&pc_id=54&pl_id=616&s_v=b5Rz2P0601xu&url=https%3A%2F%2Fitem.rakuten.co.jp%2Fnaturum-fishing%2F2938241%2F%3Frafcid%3Dwsc_i_is_c7c582dc-0853-4585-9176-66e2a26d9c5b" target="_blank" ><img src="https://thumbnail.image.rakuten.co.jp/@0_mall/naturum-fishing/cabinet/goods/029382/41_1.jpg?_ex=320x320"></a><img src="//i.moshimo.com/af/i/impression?a_id=5211705&p_id=54&pc_id=54&pl_id=616" width="1" height="1" style="border:none;">` },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3号",   type:"スーパーシャロー",     weight_g:14.5,  sink_sec_per_m:8.0,  category:"アオリイカ",    affiliate_url:`<a href="//af.moshimo.com/af/c/click?a_id=5211705&p_id=54&pc_id=54&pl_id=616&s_v=b5Rz2P0601xu&url=https%3A%2F%2Fitem.rakuten.co.jp%2Fkameya-turigu-web%2F4510001606980%2F%3Frafcid%3Dwsc_i_is_c7c582dc-0853-4585-9176-66e2a26d9c5b" target="_blank" ><img src="https://thumbnail.image.rakuten.co.jp/@0_mall/kameya-turigu-web/cabinet/newpicture/yamaria/4510001606980.jpg?_ex=320x320"></a><img src="//i.moshimo.com/af/i/impression?a_id=5211705&p_id=54&pc_id=54&pl_id=616" width="1" height="1" style="border:none;">` },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3.5号", type:"シャロー",             weight_g:20.0,  sink_sec_per_m:6.0,  category:"アオリイカ",    affiliate_url:`<a href="//af.moshimo.com/af/c/click?a_id=5211705&p_id=54&pc_id=54&pl_id=616&s_v=b5Rz2P0601xu&url=https%3A%2F%2Fitem.rakuten.co.jp%2Fyokootsurigu%2F4510001594690%2F%3Frafcid%3Dwsc_i_is_c7c582dc-0853-4585-9176-66e2a26d9c5b" target="_blank" ><img src="https://thumbnail.image.rakuten.co.jp/@0_mall/yokootsurigu/cabinet/top_4/4510001594690.jpg?_ex=320x320"></a><img src="//i.moshimo.com/af/i/impression?a_id=5211705&p_id=54&pc_id=54&pl_id=616" width="1" height="1" style="border:none;">` },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3.5号", type:"スーパーシャロー",     weight_g:19.5,  sink_sec_per_m:8.0,  category:"アオリイカ",    affiliate_url:`<a href="//af.moshimo.com/af/c/click?a_id=5211705&p_id=54&pc_id=54&pl_id=616&s_v=b5Rz2P0601xu&url=https%3A%2F%2Fitem.rakuten.co.jp%2Fkameya-turigu-web%2F4510001594799%2F%3Frafcid%3Dwsc_i_is_c7c582dc-0853-4585-9176-66e2a26d9c5b" target="_blank" ><img src="https://thumbnail.image.rakuten.co.jp/@0_mall/kameya-turigu-web/cabinet/newpicture/yamaria/4510001594799.jpg?_ex=320x320"></a><img src="//i.moshimo.com/af/i/impression?a_id=5211705&p_id=54&pc_id=54&pl_id=616" width="1" height="1" style="border:none;">` },
  { maker:"YAMASHITA", series:"エギ王K",   size:"4号",   type:"シャロー",             weight_g:24.0,  sink_sec_per_m:6.0,  category:"アオリイカ",    affiliate_url:`<a href="//af.moshimo.com/af/c/click?a_id=5211705&p_id=54&pc_id=54&pl_id=616&s_v=b5Rz2P0601xu&url=https%3A%2F%2Fitem.rakuten.co.jp%2Fnaturum%2F3531457%2F%3Frafcid%3Dwsc_i_is_c7c582dc-0853-4585-9176-66e2a26d9c5b" target="_blank" ><img src="https://thumbnail.image.rakuten.co.jp/@0_mall/naturum/cabinet/goods/035314/57_1.jpg?_ex=320x320"></a><img src="//i.moshimo.com/af/i/impression?a_id=5211705&p_id=54&pc_id=54&pl_id=616" width="1" height="1" style="border:none;">` },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3.5号", type:"黒潮スペシャル",       weight_g:22.0,  sink_sec_per_m:3.0,  category:"アオリイカ",    affiliate_url:`<a href="//af.moshimo.com/af/c/click?a_id=5345165&p_id=1225&pc_id=1925&pl_id=18502&s_v=b5Rz2P0601xu&url=https%3A%2F%2Fstore.shopping.yahoo.co.jp%2Ftsuribitokan-masuda%2F4510001609660.html" target="_blank" ><img width="200px" src="https://item-shopping.c.yimg.jp/i/n/tsuribitokan-masuda_4510001609660"></a><img src="//i.moshimo.com/af/i/impression?a_id=5345165&p_id=1225&pc_id=1925&pl_id=18502" width="1" height="1" style="border:none;">` },
  { maker:"YAMASHITA", series:"エギ王K",   size:"3.5号", type:"ディープ黒潮スペシャル", weight_g:25.0, sink_sec_per_m:2.0, category:"アオリイカ",    affiliate_url:`<a href="//af.moshimo.com/af/c/click?a_id=5345165&p_id=1225&pc_id=1925&pl_id=18502&s_v=b5Rz2P0601xu&url=https%3A%2F%2Fstore.shopping.yahoo.co.jp%2Fyfto%2F4510001609714.html" target="_blank" ><img width="200px" src="https://item-shopping.c.yimg.jp/i/n/yfto_4510001609714"></a><img src="//i.moshimo.com/af/i/impression?a_id=5345165&p_id=1225&pc_id=1925&pl_id=18502" width="1" height="1" style="border:none;">` },
  { maker:"YAMASHITA", series:"エギ王K",   size:"4号",   type:"黒潮スペシャル",       weight_g:26.0,  sink_sec_per_m:3.0,  category:"アオリイカ",    affiliate_url:`<a href="//af.moshimo.com/af/c/click?a_id=5345165&p_id=1225&pc_id=1925&pl_id=18502&s_v=b5Rz2P0601xu&url=https%3A%2F%2Fstore.shopping.yahoo.co.jp%2Ftsuribitokan-masuda%2F4510001609660.html" target="_blank" ><img width="200px" src="https://item-shopping.c.yimg.jp/i/n/tsuribitokan-masuda_4510001609660"></a><img src="//i.moshimo.com/af/i/impression?a_id=5345165&p_id=1225&pc_id=1925&pl_id=18502" width="1" height="1" style="border:none;">` },

  { maker:"YAMASHITA", series:"エギ王LIVE",   size:"2号",   type:"ベーシック", weight_g:6.5,  sink_sec_per_m:5.5, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王LIVE",   size:"2.5号", type:"ベーシック", weight_g:10.0, sink_sec_per_m:5.5, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王LIVE",   size:"3号",   type:"ベーシック", weight_g:15.0, sink_sec_per_m:3.5, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王LIVE",   size:"3.5号", type:"ベーシック", weight_g:21.0, sink_sec_per_m:3.0, category:"アオリイカ", affiliate_url:"" },

  { maker:"YAMASHITA", series:"エギ王SEARCH", size:"2.5号", type:"ベーシック", weight_g:12.0, sink_sec_per_m:3.6, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王SEARCH", size:"3号",   type:"ベーシック", weight_g:17.0, sink_sec_per_m:3.2, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王SEARCH", size:"3.5号", type:"ベーシック", weight_g:24.0, sink_sec_per_m:2.8, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王SEARCH", size:"3号",   type:"シャロー",   weight_g:15.5, sink_sec_per_m:4.5, category:"アオリイカ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王SEARCH", size:"3.5号", type:"シャロー",   weight_g:21.0, sink_sec_per_m:4.5, category:"アオリイカ", affiliate_url:"" },

  { maker:"YAMASHITA", series:"エギ王TR", size:"3号",   type:"TR", weight_g:21.0, sink_sec_per_m:1.5, category:"ティップラン", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギ王TR", size:"3.5号", type:"TR", weight_g:27.0, sink_sec_per_m:1.2, category:"ティップラン", affiliate_url:"" },

  { maker:"YAMASHITA", series:"NAORY レンジ シャロー",   size:"1.5号",  type:"シャロー",         weight_g:3.3,  sink_sec_per_m:8.5,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ シャロー",   size:"1.8号",  type:"シャロー",         weight_g:5.0,  sink_sec_per_m:10.0, category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ シャロー",   size:"2.2B号", type:"シャロー",         weight_g:8.0,  sink_sec_per_m:5.0,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ ベーシック", size:"1.5号",  type:"ベーシック",       weight_g:3.8,  sink_sec_per_m:4.5,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ ベーシック", size:"1.8号",  type:"ベーシック",       weight_g:6.0,  sink_sec_per_m:3.2,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ ベーシック", size:"2.2B号", type:"ベーシック",       weight_g:9.0,  sink_sec_per_m:2.8,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ ディープ",   size:"1.5号",  type:"ディープ",         weight_g:4.7,  sink_sec_per_m:3.0,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ ディープ",   size:"1.8号",  type:"ディープ",         weight_g:7.0,  sink_sec_per_m:2.5,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"NAORY レンジ ディープ",   size:"2.2B号", type:"ディープ",         weight_g:10.5, sink_sec_per_m:2.2,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"ナオリー サイトハンター", size:"1.0号",  type:"ベーシックシャロー", weight_g:1.5, sink_sec_per_m:8.5,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"ナオリー サイトハンター", size:"1.3号",  type:"ベーシックシャロー", weight_g:2.3, sink_sec_per_m:8.0,  category:"ライトエギング", affiliate_url:"" },
  { maker:"YAMASHITA", series:"エギーノもぐもぐサーチ",  size:"3.2号",  type:"キビナゴ装着時",   weight_g:20.0, sink_sec_per_m:2.8,  category:"入門／エサ巻き系", affiliate_url:"" },
  { maker:"YAMASHITA", series:"ホバー", size:"2.0号", type:"単体", weight_g:6.0, sink_sec_per_m:8.0, category:"オモリグ", affiliate_url:"" },
  { maker:"YAMASHITA", series:"ホバー", size:"2.5号", type:"単体", weight_g:9.0, sink_sec_per_m:8.0, category:"オモリグ", affiliate_url:"" },

  /* ---------- DUEL ---------- */
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ",         size:"2.5号", type:"ベーシック", weight_g:10.0, sink_sec_per_m:5.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ",         size:"3.0号", type:"ベーシック", weight_g:14.0, sink_sec_per_m:3.7,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ",         size:"3.5号", type:"ベーシック", weight_g:17.0, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター",           size:"2.5号", type:"ベーシック", weight_g:10.0, sink_sec_per_m:5.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター",           size:"3.0号", type:"ベーシック", weight_g:14.5, sink_sec_per_m:3.5,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター",           size:"3.5号", type:"ベーシック", weight_g:19.0, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"Ebi Q",                              size:"3.0号", type:"ベーシック", weight_g:15.5, sink_sec_per_m:4.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"Ebi Q",                              size:"3.5号", type:"ベーシック", weight_g:20.5, sink_sec_per_m:3.5,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ マグネットTG（マグパタ）", size:"3.0号", type:"ベーシック", weight_g:15.0, sink_sec_per_m:3.8,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ マグネットTG（マグパタ）", size:"3.5号", type:"ベーシック", weight_g:18.5, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"EQ（Egiオリジナル）",                size:"3.0号", type:"ベーシック", weight_g:14.5, sink_sec_per_m:3.7,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"EQ（Egiオリジナル）",                size:"3.5号", type:"ベーシック", weight_g:19.0, sink_sec_per_m:3.3,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"LQ ダーター",                        size:"3.0号", type:"ベーシック", weight_g:14.0, sink_sec_per_m:3.8,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"LQ ダーター",                        size:"3.5号", type:"ベーシック", weight_g:18.0, sink_sec_per_m:3.3,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ スロー",   size:"3.0号", type:"スロー",     weight_g:13.0, sink_sec_per_m:6.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ スロー",   size:"3.5号", type:"スロー",     weight_g:15.5, sink_sec_per_m:6.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ ラトル",   size:"2.5号", type:"ラトル",     weight_g:10.0, sink_sec_per_m:3.9,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ ラトル",   size:"3.0号", type:"ラトル",     weight_g:14.0, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト 喰わせ ラトル",   size:"3.5号", type:"ラトル",     weight_g:17.0, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト プラス",          size:"3.0号", type:"ベーシック", weight_g:14.5, sink_sec_per_m:3.5,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ キャスト プラス",          size:"3.5号", type:"ベーシック", weight_g:19.5, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター SS",        size:"3.0号", type:"SS",         weight_g:13.0, sink_sec_per_m:8.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター SS",        size:"3.5号", type:"SS",         weight_g:17.5, sink_sec_per_m:8.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター ラトル",    size:"2.5号", type:"ラトル",     weight_g:10.0, sink_sec_per_m:5.0,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター ラトル",    size:"3.0号", type:"ラトル",     weight_g:14.5, sink_sec_per_m:3.5,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"イージーQ ダートマスター ラトル",    size:"3.5号", type:"ラトル",     weight_g:19.0, sink_sec_per_m:3.2,  category:"アオリイカ", affiliate_url:"" },
  { maker:"DUEL", series:"Ebi Q TR",                           size:"3.0号", type:"TR",         weight_g:23.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DUEL", series:"Ebi Q TR",                           size:"3.5号", type:"TR",         weight_g:28.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },

  /* ---------- DAIWA ---------- */
  { maker:"DAIWA", series:"エメラルダス アモラスジョイント",             size:"2.5号",     type:"ベーシック", weight_g:11.0, sink_sec_per_m:4.75, category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス アモラスジョイント",             size:"3.0号",     type:"ベーシック", weight_g:13.5, sink_sec_per_m:4.25, category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス アモラスジョイント",             size:"3.5号",     type:"ベーシック", weight_g:22.5, sink_sec_per_m:3.75, category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス アモラスジョイント TypeS",       size:"2.5号",     type:"TypeS",      weight_g:10.0, sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス アモラスジョイント TypeS",       size:"3.0号",     type:"TypeS",      weight_g:12.5, sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス アモラスジョイント TypeS",       size:"3.5号",     type:"TypeS",      weight_g:21.0, sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス シャイン LC レーザーインパクト", size:"2.5号",     type:"ベーシック", weight_g:12.0, sink_sec_per_m:4.75, category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス シャイン LC レーザーインパクト", size:"3.0号",     type:"ベーシック", weight_g:14.0, sink_sec_per_m:4.25, category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス シャイン LC レーザーインパクト", size:"3.5号",     type:"ベーシック", weight_g:18.5, sink_sec_per_m:3.75, category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダスシャインLC TypeS",                size:"3.5号",     type:"TypeS",      weight_g:18.4, sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル",              size:"2.0号",     type:"ラトル",     weight_g:6.5,  sink_sec_per_m:6.5,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル",              size:"2.5号",     type:"ラトル",     weight_g:10.0, sink_sec_per_m:5.5,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル",              size:"3.0号",     type:"ラトル",     weight_g:14.5, sink_sec_per_m:4.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル",              size:"3.5号",     type:"ラトル",     weight_g:21.5, sink_sec_per_m:3.5,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル typeS",        size:"2.5号",     type:"ラトルTypeS", weight_g:9.5, sink_sec_per_m:6.5,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル typeS",        size:"3.0号",     type:"ラトルTypeS", weight_g:14.0,sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス フォールLC ラトル typeS",        size:"3.5号",     type:"ラトルTypeS", weight_g:20.5,sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ダートLC",                       size:"3.0号",     type:"ベーシック", weight_g:16.0, sink_sec_per_m:4.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダスダートLC TypeS",                  size:"3.5号",     type:"TypeS",      weight_g:19.0, sink_sec_per_m:6.0,  category:"アオリイカ",  affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボートジョイント",               size:"3.0号-25g", type:"ボート",     weight_g:25.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボートジョイント",               size:"3.5号-30g", type:"ボート",     weight_g:30.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II（ノーマルバージョン）", size:"2.75号-25g", type:"ボート",    weight_g:25.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II（ノーマルバージョン）", size:"3号-25g",   type:"ボート",    weight_g:25.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II（ノーマルバージョン）", size:"3号-35g",   type:"ボート",    weight_g:35.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II RV（ラトルバージョン）", size:"2.75号-25g", type:"ラトル",  weight_g:25.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II RV（ラトルバージョン）", size:"3号-25g",   type:"ラトル",  weight_g:25.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II RV（ラトルバージョン）", size:"3号-35g",   type:"ラトル",  weight_g:35.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II / ボート II RV 3.5-50", size:"3.5号-50g", type:"ボート",  weight_g:50.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダス ボート II / ボート II RV 3.5-50", size:"3.5号-50g", type:"ラトル",  weight_g:50.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダスボート RV（ラトルバージョン）",    size:"3.0号-25g", type:"ラトル",  weight_g:25.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },
  { maker:"DAIWA", series:"エメラルダスボート RV（ラトルバージョン）",    size:"3.5号-30g", type:"ラトル",  weight_g:30.0, sink_sec_per_m:null, category:"ティップラン", affiliate_url:"" },

  /* ---------- SHIMANO ---------- */
  { maker:"SHIMANO", series:"セッピー",                             size:"1.5号", type:"ベーシック",       weight_g:4.5,  sink_sec_per_m:3.7, category:"ライトエギング", affiliate_url:"" },
  { maker:"SHIMANO", series:"セッピー",                             size:"1.8号", type:"ベーシック",       weight_g:7.0,  sink_sec_per_m:3.5, category:"ライトエギング", affiliate_url:"" },
  { maker:"SHIMANO", series:"セッピー",                             size:"2.2号", type:"ベーシック",       weight_g:9.0,  sink_sec_per_m:2.2, category:"ライトエギング", affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ フラッシュブースト",          size:"2.5号", type:"ベーシック",       weight_g:10.0, sink_sec_per_m:4.0, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ フラッシュブースト",          size:"3.0号", type:"ベーシック",       weight_g:15.0, sink_sec_per_m:3.0, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ フラッシュブースト",          size:"3.5号", type:"ベーシック",       weight_g:19.0, sink_sec_per_m:3.7, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ エクスカウンター",            size:"3.5号", type:"ベーシック",       weight_g:19.0, sink_sec_per_m:3.7, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ エクスカウンター",            size:"3.8号", type:"ベーシック",       weight_g:24.0, sink_sec_per_m:3.5, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ シャロー",                    size:"3.5号", type:"ベーシック",       weight_g:18.5, sink_sec_per_m:6.0, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ シャロー フラッシュブースト", size:"3.0号", type:"フラッシュブースト", weight_g:13.8, sink_sec_per_m:5.4, category:"アオリイカ",  affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ シャロー フラッシュブースト", size:"3.5号", type:"フラッシュブースト", weight_g:18.5, sink_sec_per_m:6.0, category:"アオリイカ",  affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ ディープ フラッシュブースト", size:"3.5号", type:"ディープ",         weight_g:23.0, sink_sec_per_m:1.9, category:"アオリイカ",    affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ ロングアピール ジェットブースト", size:"3.0号", type:"ロングアピール", weight_g:13.0, sink_sec_per_m:4.2, category:"アオリイカ", affiliate_url:"" },
  { maker:"SHIMANO", series:"クリンチ ロングアピール ジェットブースト", size:"3.5号", type:"ロングアピール", weight_g:17.0, sink_sec_per_m:7.4, category:"アオリイカ", affiliate_url:"" },
];
